### ISSUE TITLE
.travis.yml remove_includes is not well documented

### ISSUE THREAD

**Issue by ghoneycutt** [puppetlabs/pdk-templates#225] opened 2019-03-22 15:38 UTC
It is not clear how to remove the includes.

**Comment by natemccurdy** [comment] 2019-04-17 05:06
For reference, I had to [figure this out recently](https://github.com/puppetlabs/pdk-templates/pull/178#issuecomment-483937176) and thought I'd share a working example:

```
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec RUBYGEMS_VERSION=2.7.8
      rvm: 2.1.9
      stage: spec
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
```

To remove an include, you have to list it **exactly** the same as it is seen in `.travis.yml`. All the keys are needed and the key's values must be an exact match.

**Comment by DavidS** [comment] 2021-01-18 11:37
This is a duplicate of #226 - as was said there the current approach is not very ergonomic and could do with an overhaul.

**Closed by DavidS** 2021-01-18 11:37 UTC
